# starship.toml
# vim: ft=toml

#   __|    \    _ \  |      _ \   __| __ __| __ __|
#  (      _ \     /  |     (   | (_ |    |      |
# \___| _/  _\ _|_\ ____| \___/ \___|   _|     _|


# ------------------------------
# Staraship Prompt Configuration
# ------------------------------
format = """
$time\
$shell\
$jobs\
$username\
$sudo\
$custom\
$hostname\
$os\
$localip\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$battery\
$status\
$container\
$cmd_duration\

$line_break\
$directory\

$line_break\
$shlvl\
$character"""

[line_break]
disabled = false

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[shell]
disabled = false

[jobs]
format = '[$symbol\([$number](yellow)\)]($style) '
number_threshold = 1
symbol = "jbs"
style = "white"

[shlvl]
disabled = false
format = '[$shlvl$symbol]($style)'
style = 'bold green'
repeat = true
symbol = '❯'
repeat_offset = 1
threshold = 0

[cmd_duration]
format = '\[[$duration]($style)\]'
style = 'white'
min_time = 0
show_milliseconds = true

[time]
disabled = false
format = '[$time]($style) '
use_12hr = true
utc_time_offset = 'local'
style = 'green'

[username]
style_user = 'yellow bold'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true

[sudo]
format = '[\(](bold yellow)[$symbol]($style)[\)](bold yellow)'
symbol = "sudo"
disabled = false
style = 'red'

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 100
truncate_to_repo = false
truncation_symbol = '…/'
style = 'cyan'
repo_root_style = 'green'
read_only = ' [READ]'
read_only_style = 'bold red'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '[$all_status$ahead_behind](purple)'
staged = 'stg\([$count](blue)\) '
untracked = 'unt\([$count](blue)\) '
modified = 'mod\([$count](blue)\) '
renamed = 'ren\([$count](blue)\) '
conflicted = 'cnf\([$count](blue)\) '
deleted = 'del\([$count](blue)\) '
stashed = 'sts\([$count](blue)\) '
up_to_date = 'ups\([✔](blue)\) '
ahead = 'ups\([⇡](blue)\) '
behind = 'ups\([⇣](blue)\) '
diverged = 'ups\([⇕](blue)\) '

[hostname]
ssh_only = false
format = ' [$hostname](bold blue)'
disabled = true

[custom.hostname-base]
command = 'hostname'
format = ' [$output](bold blue)'
when = '[[ ! $(hostname) == *"dev-dsk"* ]]'

[custom.hostname-devdsk]
command = 'hostname'
format = ' [$output](bold purple)'
when = '[[ $(hostname) == *"dev-dsk"* ]]'

[os]
format = '[\(](bold blue)[$symbol]($style)[\)](bold blue) '
disabled = false
style = 'cyan'

[os.symbols]
Alpaquita = "alq"
Alpine = "alp"
Amazon = "amz"
Android = "andr"
Arch = "rch"
Artix = "atx"
CentOS = "cent"
Debian = "deb"
DragonFly = "dfbsd"
Emscripten = "emsc"
EndeavourOS = "ndev"
Fedora = "fed"
FreeBSD = "fbsd"
Garuda = "garu"
Gentoo = "gent"
HardenedBSD = "hbsd"
Illumos = "lum"
Linux = "lnx"
Mabox = "mbox"
Macos = "macos"
Manjaro = "mjo"
Mariner = "mrn"
MidnightBSD = "mid"
Mint = "mint"
NetBSD = "nbsd"
NixOS = "nix"
OpenBSD = "obsd"
OpenCloudOS = "ocos"
openEuler = "oeul"
openSUSE = "osuse"
OracleLinux = "orac"
Pop = "pop"
Raspbian = "rasp"
Redhat = "rhl"
RedHatEnterprise = "rhel"
Redox = "redox"
Solus = "sol"
SUSE = "suse"
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[aws]
format = '[[via ](white)$symbol ([p\(](yellow)[$profile](green)[\)](yellow) )([r\(](yellow)[$region](green)[\)](yellow) )([d\(](yellow)[$duration](green)[\)](yellow) )]($style)'
symbol = "aws"
expiration_symbol = "cred expired"

[azure]
symbol = "az "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[golang]
symbol = "go "

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[raku]
symbol = "raku "

[rlang]
symbol = "r "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
