# starship.toml
# vim: ft=toml

#   __|    \    _ \  |      _ \   __| __ __| __ __|
#  (      _ \     /  |     (   | (_ |    |      |
# \___| _/  _\ _|_\ ____| \___/ \___|   _|     _|


# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# ----------------
# Catppuccin Theme
# ----------------
# Set user-defined palette
# Palettes must be defined AFTER this line
# palette = "catppuccin_mocha"

# Palette definitions
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


# ------------------------------
# Staraship Prompt Configuration
# ------------------------------
format = """
$time\
$shell\
$jobs\
$username\
$sudo\
$custom\
$hostname\
$os\
$localip\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$battery\
$status\
$container\
$cmd_duration\

$line_break\
$directory\

$line_break\
$shlvl\
$character"""

[line_break]
disabled = false

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[shell]
disabled = false

[jobs]
format = '[$symbol\([$number](yellow)\)]($style) '
number_threshold = 1
symbol = "jbs"
style = "white"

[shlvl]
disabled = false
format = '[$shlvl$symbol]($style)'
style = 'bold green'
repeat = true
symbol = '❯'
repeat_offset = 1
threshold = 0

[cmd_duration]
format = '\[[$duration]($style)\]'
style = 'white'
min_time = 0
show_milliseconds = true

[time]
disabled = false
format = '[$time]($style) '
use_12hr = true
utc_time_offset = 'local'
style = 'green'

[username]
style_user = 'yellow bold'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true

[sudo]
format = '[\(](bold yellow)[$symbol]($style)[\)](bold yellow)'
symbol = "sudo"
disabled = false
style = 'red'

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 100
truncate_to_repo = false
truncation_symbol = '…/'
style = 'cyan'
repo_root_style = 'green'
read_only = ' [READ]'
read_only_style = 'bold red'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '[$all_status$ahead_behind](purple)'
staged = 'stg\([$count](blue)\) '
untracked = 'unt\([$count](blue)\) '
modified = 'mod\([$count](blue)\) '
renamed = 'ren\([$count](blue)\) '
conflicted = 'cnf\([$count](blue)\) '
deleted = 'del\([$count](blue)\) '
stashed = 'sts\([$count](blue)\) '
up_to_date = 'ups\([✔](blue)\) '
ahead = 'ups\([⇡](blue)\) '
behind = 'ups\([⇣](blue)\) '
diverged = 'ups\([⇕](blue)\) '

[hostname]
ssh_only = false
format = ' [$hostname](bold blue)'
disabled = true

[custom.hostname-base]
command = 'hostname'
format = ' [$output](bold blue)'
when = '[[ ! $(hostname) == *"dev-dsk"* && ! $(hostname) == *"compute.internal"* ]]'

[custom.hostname-devdsk]
command = 'hostname'
format = ' [$output](bold purple)'
when = '[[ $(hostname) == *"dev-dsk"* || $(hostname) == *"compute.internal"* ]]'

[os]
format = '[\(](bold blue)[$symbol]($style)[\)](bold blue) '
disabled = false
style = 'cyan'

[os.symbols]
Alpaquita = "alq"
Alpine = "alp"
Amazon = "amz"
Android = "andr"
Arch = "rch"
Artix = "atx"
CentOS = "cent"
Debian = "deb"
DragonFly = "dfbsd"
Emscripten = "emsc"
EndeavourOS = "ndev"
Fedora = "fed"
FreeBSD = "fbsd"
Garuda = "garu"
Gentoo = "gent"
HardenedBSD = "hbsd"
Illumos = "lum"
Linux = "lnx"
Mabox = "mbox"
Macos = "macos"
Manjaro = "mjo"
Mariner = "mrn"
MidnightBSD = "mid"
Mint = "mint"
NetBSD = "nbsd"
NixOS = "nix"
OpenBSD = "obsd"
OpenCloudOS = "ocos"
openEuler = "oeul"
openSUSE = "osuse"
OracleLinux = "orac"
Pop = "pop"
Raspbian = "rasp"
Redhat = "rhl"
RedHatEnterprise = "rhel"
Redox = "redox"
Solus = "sol"
SUSE = "suse"
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[aws]
format = '[[via ](white)$symbol ([p\(](yellow)[$profile](green)[\)](yellow) )([r\(](yellow)[$region](green)[\)](yellow) )([d\(](yellow)[$duration](green)[\)](yellow) )]($style)'
symbol = "aws"
expiration_symbol = "cred expired"

[azure]
symbol = "az "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[golang]
symbol = "go "

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[raku]
symbol = "raku "

[rlang]
symbol = "r "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
